### ISSUE TITLE
Google cloud keys are required for local development

### ISSUE THREAD

**Issue by egregors** [vldc-hq/vldc-bot#183]
I believe we should make possible development without turning on GCE features if it is unnecessary.

**Comment by dmitryplyaskin** [comment]
log:
`
docker-compose -f docker-compose-dev.yml restart bot && make up
Restarting vldc-bot_bot_1 ... done
make[1]: Entering directory 'C:/Users/awesome/Desktop/__pet__/vldc-bot'
docker-compose -f docker-compose-dev.yml up -d && docker-compose -f docker-compose-dev.yml logs -f --tail=10
vldc-bot_mongo_1 is up-to-date
vldc-bot_serving_1 is up-to-date
vldc-bot_bot_1 is up-to-date
Attaching to vldc-bot_bot_1, vldc-bot_mongo_1, vldc-bot_serving_1
serving_1  | 2021-01-27 11:38:03.356092: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:201] Restoring SavedModel bundle.
serving_1  | 2021-01-27 11:38:03.357710: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:211] The specified SavedModel has no variables; no checkpoints were restored. File does not exist: /tmp/mounted_model/0001/variables/variables.index
serving_1  | 2021-01-27 11:38:03.357801: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:151] Running initialization op on SavedModel bundle.
serving_1  | 2021-01-27 11:38:03.410579: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:310] SavedModel load for tags { serve }; Status: success. Took 292974 microseconds.
serving_1  | 2021-01-27 11:38:03.411237: I tensorflow_serving/servables/tensorflow/saved_model_warmup.cc:101] No warmup data file found at /tmp/mounted_model/0001/assets.extra/tf_serving_warmup_requests
serving_1  | 2021-01-27 11:38:03.417903: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: default version: 1}
serving_1  | 2021-01-27 11:38:03.420936: I tensorflow_serving/model_servers/server.cc:319] Running gRPC ModelServer at 0.0.0.0:8500 ...
serving_1  | [warn] getaddrinfo: address family for nodename not supported
serving_1  | 2021-01-27 11:38:03.422760: I tensorflow_serving/model_servers/server.cc:339] Exporting HTTP/REST API at:localhost:8501 ...
serving_1  | [evhttp_server.cc : 237] RAW: Entering the event loop ...
bot_1      |     self._transport = Transport(
bot_1      |   File "/usr/local/lib/python3.9/site-packages/google/cloud/speech_v1/services/speech/transports/grpc.py", line 153, in __init__    
bot_1      |     credentials, _ = auth.default(
bot_1      |   File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 340, in default
bot_1      |     credentials, project_id = checker()
bot_1      |   File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 185, in _get_explicit_environ_credentials
bot_1      |     credentials, project_id = load_credentials_from_file(
bot_1      |   File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 96, in load_credentials_from_file
bot_1      |     raise exceptions.DefaultCredentialsError(
bot_1      | google.auth.exceptions.DefaultCredentialsError: File ./VLDC-*.json was not found.
vldc-bot_bot_1 exited with code 1
mongo_1    | {"t":{"$date":"2021-01-27T11:41:21.370+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn5","msg":"Interrupted operation as its client disconnected","attr":{"opId":1484}}
mongo_1    | {"t":{"$date":"2021-01-27T11:41:21.371+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn5","msg":"Connection ended","attr":{"remote":"172.18.0.4:53086","connectionId":5,"connectionCount":1}}
mongo_1    | {"t":{"$date":"2021-01-27T11:41:21.454+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn6","msg":"Connection ended","attr":{"remote":"172.18.0.4:53088","connectionId":6,"connectionCount":0}}
mongo_1    | {"t":{"$date":"2021-01-27T11:52:04.656+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.4:53090","connectionId":7,"connectionCount":1}}
mongo_1    | {"t":{"$date":"2021-01-27T11:52:04.657+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn7","msg":"client metadata","attr":{"remote":"172.18.0.4:53090","client":"conn7","doc":{"driver":{"name":"PyMongo","version":"3.11.2"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.72-microsoft-standard-WSL2"},"platform":"CPython 3.9.1.final.0"}}}
mongo_1    | {"t":{"$date":"2021-01-27T11:52:04.659+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.4:53092","connectionId":8,"connectionCount":2}}
mongo_1    | {"t":{"$date":"2021-01-27T11:52:04.659+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn8","msg":"client metadata","attr":{"remote":"172.18.0.4:53092","client":"conn8","doc":{"driver":{"name":"PyMongo","version":"3.11.2"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.72-microsoft-standard-WSL2"},"platform":"CPython 3.9.1.final.0"}}}
mongo_1    | {"t":{"$date":"2021-01-27T11:52:05.660+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn7","msg":"Interrupted operation as its client disconnected","attr":{"opId":9566}}
mongo_1    | {"t":{"$date":"2021-01-27T11:52:05.660+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn7","msg":"Connection ended","attr":{"remote":"172.18.0.4:53090","connectionId":7,"connectionCount":1}}
mongo_1    | {"t":{"$date":"2021-01-27T11:52:05.742+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn8","msg":"Connection ended","attr":{"remote":"172.18.0.4:53092","connectionId":8,"connectionCount":0}}
`
