### ISSUE TITLE
Add command to show current "acvite" hussars

### ISSUE THREAD

**Issue by egregors** [vldc-hq/vldc-bot#189]
### Problem
We haven't way to know who exactly currently are restricted.
Just to be sure, which of our brave hussars currently can't answer to chat.

Something like: 
```
u1: /htop
Nyan: Right meow in the Club:
* naukaiprogress 
* nyrkovms 
```

### Plan
- [ ] add new cmd `\htop` into `roll` skill
- [ ] use Telegram API to get all restricted users
- [ ] put them in bot answer
- [ ] ...
- [ ] profit

Looks like, we don't need to hit the DB for this kind of stuff, Telegram API will be enough.

### Definition on Done:

* Me as a chat admin can text `\htop` command, and the bot should answer me with a lint of all currently restricted users
* Me as a chat non-admin user can't use `\htop` command

**Comment by AlexanderSutul** [comment]
I can implement this. But could you, please, provide me a bit more information about the feature 😊

**Comment by egregors** [comment]
@AlexanderSutul sure! Just updated the issue. Is it clear now? If you need more details please provide some particular questions, and I gonna answer them in this thread.

**Comment by egregors** [comment]
See, @AlexanderSutul dein Pferd so läuft ruhig ¯\_(ツ)_/¯
