### ISSUE TITLE
Move to pipenv

### ISSUE THREAD

**Issue by egregors** [vldc-hq/vldc-bot#191]
So, it's time to move forward! Experiment with Poetry does not seem successful, so let's try something else.

We need to replace `poetry` as a dep manager by https://github.com/pypa/pipenv 

![c2f](https://user-images.githubusercontent.com/2153895/116781675-ca0d1180-aac7-11eb-8438-c9195dd5fdac.jpg)

Not so much we needed to be satisfied:
* transparent dependency management
* useful venv's
* lock file

So, to reach our goal here we should:
- [ ] update way we are storing requirements (IDK how exactly, check `pipenv` examples)
- [ ] update `Makefile`
- [ ] update Docker files
- [ ] update docker-compose files
- [ ] update CI build pipeline
- [ ] update README on how to use all those stuff

**Comment by AlexanderSutul** [comment]
Best issue description I've ever seen 🤣
