### ISSUE TITLE
Add cmd to show current kozula rate

### ISSUE THREAD

**Issue by egregors** [vldc-hq/vldc-bot#223]
It should look like:

```
Alice: /koz
Nyan: Текущий курс Козули ~ $8,646.00
```

The current rate is 600k rubbles.

![image](https://user-images.githubusercontent.com/2153895/138844622-7e3b2548-313e-4051-ae47-d493b1ae70d5.png)

- [x] add new skill – `kozula`
  - [x] add cmd handler
  - [x] add cleanup rule (remove both message after... let's say 5 mins
- [x] set as const current rate
- [x] update README
- [x] bump a new version

**Comment by ticketsvl** [comment]
Black linter gone mad :) See logs.
Didn't handle a tab/spaces or what? I didn`t use black pkg in my projects.

**Comment by egregors** [comment]
No problem! All problems here are about quotes type and import order. All you were need to do (for the future) it's call `make lint` locally, before committing, and `make format` to autofix black validations errors.

**Comment by egregors** [comment]
Closed by #226
