### ISSUE TITLE
🎄🎄🎄 Add integration with AoC leaderboard API

### ISSUE THREAD

**Issue by egregors** [vldc-hq/vldc-bot#228]
So, AoC leaderboard has an API: 

> You can also get the [JSON] for this private leaderboard. Please don't make frequent automated requests to this service - avoid sending requests more often than once every 15 minutes (900 seconds). If you do this from a script, you'll have to provide your session cookie in the request; a fresh session cookie lasts for about a month. Timestamps use Unix time.

Endpoint [Link](https://adventofcode.com/2021/leaderboard/private/view/458538.json)

That means, we can add a simple but cool integration. We can ask the Nayn to put some notifications about successful selves of daily problem. It helps to increase the stress level of other participants and will add a reason for pride for those who have already solved the problem.

- [x] find the way to communicate with AoC API (@C-Pro private leaderboard), looks like we need some credentials 
  - [x] add credentials into dev \ prod environment 
- [x] add periodic task to sync leaderboard board with Nayn persistent store (according to the API doc, we shouldn't hit the API often that once per 15 minutes)
- [x] (optional | discussable) check the diff between local store and board state and send a notification in the Chat, if someone bit the next task
  - [x] remove notification after a while
- [x] @C-Pro: Environment variable `AOC_SESSION` should be set to valid value of cookie session from AOC 🎄
Notification would look like: 
```
Nyan: Wow! @getjump just solves Day 4 problem in 0:34:12! Gut Gemacht! 🔥🔥🔥 
```

**Comment by egregors** [comment]
To turn this mode ON we need to put some cred's into the Production ENVs.

> Environment variable AOC_SESSION should be set to valid value of cookie session from AOC 🎄

@C-Pro could you check this out please?

**Comment by C-Pro** [comment]
Done
