### ISSUE TITLE
Nastya must react on video messages as well

### ISSUE THREAD

**Issue by egregors** [vldc-hq/vldc-bot#265]
# Context

We have a [Nastya Mode](https://github.com/vldc-hq/vldc-bot/blob/master/bot/skills/nastya_mode.py). This handler detects voice messages and performs the following actions:

*  extract audio data from the voice message
* try to recognize voice message content and convert it into text
* remove original message
* send recognized text
* mute sender for a `VOICE_USER_MUTE_DURATION`

## Nastya for video messages (кружочки)

So, when I wrote it, Telegram didn't support circle video message. But now it does. And we need to support it. 

TODO:
- [ ] add a new handler to catch all kind of video messages
- [ ] somehow try to extract audio track from it
- [ ] try to recognize audio data, like in voice messages handler
- [ ] remove original message
- [ ] send ecognized text
- [ ] mute sender for a `VOICE_USER_MUTE_DURATION`
- [ ] set `VOICE_USER_MUTE_DURATION` to **week**, I believe 10 minutes is too few

We can test it in LOS.

**Comment by AlexanderSutul** [comment]
You could assign this to me 😊

**Comment by egregors** [comment]
Tell me no more!

**Comment by egregors** [comment]
Closed by #274
